# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/btnguyen2k/prista
    steps:
      - checkout
      - run:
          name: Build Project
          command: go build main.go
  build_docker_image:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/btnguyen2k/prista
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: export CI_PROJECT_VERSION=`echo $CIRCLE_TAG | cut -d'-' -f 2` && docker build --force-rm -t prista:$CI_PROJECT_VERSION . && docker images
workflows:
  version: 2
  build:
    jobs:
      - build
